// Generated by CoffeeScript 2.0.0-beta6
angular.module('app').controller('BooksController', function ($scope, BookResource) {
  return $scope.books = BookResource.query();
});

/*
//@ sourceMappingURL=books_controller.coffee.map
*/
